### ISSUE TITLE
Running game error after string import

### ISSUE THREAD

**Issue by xjgames** [KovacsGG/pyI2L#2]
Running game error after string import
![1](https://github.com/user-attachments/assets/cf10c1ef-b8b9-4af2-a847-510f7270b423)
![4](https://github.com/user-attachments/assets/bfa0d832-bf65-47f6-9dbd-c032aa476110)

![3](https://github.com/user-attachments/assets/c96065f2-51a6-4b08-b190-78fc64051932)

**Comment by KovacsGG** [comment]
Thanks for the report. I can probably check out the game on Monday. In the meantime:

1. Please send me your modified CSV.
2. Try extracting with `pyI2L.exe -f rawCSV` and applying with `pyI2L.exe -f rawCSV -a resources.assets.csv`. You have to use the same format option for extraction and application, so both of these steps are mandatory, you can't use the CSV you already have. You might be able to convert it yourself, however, once you see how it looks.

**Comment by xjgames** [comment]
[resources.assets.zip](https://github.com/user-attachments/files/16191487/resources.assets.zip)
Successfully imported using the second method

**Comment by xjgames** [comment]
> [resources.assets.zip](https://github.com/user-attachments/files/16191487/resources.assets.zip) 使用第二种方法导入成功



> 谢谢你的报告。我可能在周一可以看看这场比赛。与此同时：
> 
> 1. 请将您修改后的 CSV 发送给我。
> 2. 尝试使用 提取`pyI2L.exe -f rawCSV`并应用`pyI2L.exe -f rawCSV -a resources.assets.csv`。提取和应用时必须使用相同的格式选项，因此这两个步骤都是必需的，您不能使用已有的 CSV。不过，一旦您看到它的样子，您也许可以自己转换它。

**Comment by xjgames** [comment]
> 谢谢你的回馈。我可能会在周一看看这部分影响。与此同时：
> 
> 1. 请将您修改后的 CSV 发送给我。
> 2. 尝试使用引入`pyI2L.exe -f rawCSV`并应用`pyI2L.exe -f rawCSV -a resources.assets.csv`。引入和应用时必须使用相同的格式选项，因此这两个步骤都是必需的，您不能使用已有的CSV。不过，一旦您看到它的例子，您也许可以自己转换它。

[resources.assets.zip](https://github.com/user-attachments/files/16191526/resources.assets.zip)


Successfully imported using the second method

**Comment by xjgames** [comment]
> Thanks for the report. I can probably check out the game on Monday. In the meantime:
> 
> 1. Please send me your modified CSV.
> 2. Try extracting with `pyI2L.exe -f rawCSV` and applying with `pyI2L.exe -f rawCSV -a resources.assets.csv`. You have to use the same format option for extraction and application, so both of these steps are mandatory, you can't use the CSV you already have. You might be able to convert it yourself, however, once you see how it looks.

[resources.assets.zip](https://github.com/user-attachments/files/16191540/resources.assets.zip)


Successfully imported using the second method
